package de.frank.invoice.worker.application.export;

import java.util.List;

/**
 * Generates one concrete invoice file format.
 */
public interface InvoiceExporter {

    /**
     * Returns the format generated by this exporter.
     *
     * @return supported format
     */
    InvoiceExportFormat format();

    /**
     * Generates file bytes for the supplied rows.
     *
     * @param rows deterministic export rows
     * @return generated file bytes
     */
    byte[] export(List<InvoiceExportRow> rows);
}
